In [1]:
import pandas as pd
a = pd.read_csv('D:\Python\TekWorks\Week_3\messy_employee_dataset_1000_rows.csv')
df = pd.DataFrame(a)
df.head()

<>:2: SyntaxWarning: invalid escape sequence '\P'
<>:2: SyntaxWarning: invalid escape sequence '\P'
C:\Users\vinee\AppData\Local\Temp\ipykernel_13368\3028955581.py:2: SyntaxWarning: invalid escape sequence '\P'
  a = pd.read_csv('D:\Python\TekWorks\Week_3\messy_employee_dataset_1000_rows.csv')

,user_id,age,salary,department,join_date,city,performance_score,experience_years,is_active
0,user_0,-5,₹50000,HR,2020/12/01,DELHI,3,five,True
1,U1001,30,45000,Finance,15/02/2021,Delhi,3,1,yes
2,U1002,30,25000,HR,NaN,Delhi,excellent,10,False
3,NaN,unknown,NaN,HR,invalid,Hyderabad,excellent,5,yes
4,NaN,NaN,120000.75,IT,NaN,DELHI,NaN,-1,False

In [2]:
df.columns

Index(['user_id', 'age', 'salary', 'department', 'join_date', 'city',
       'performance_score', 'experience_years', 'is_active'],
      dtype='str')

In [3]:
df.shape

(1000, 9)

In [4]:
a = df.isnull().sum()
print((a/1000)*100)

user_id              51.0
age                  11.4
salary               31.1
department           14.1
join_date            21.9
city                 14.9
performance_score    10.1
experience_years     12.7
is_active            20.0
dtype: float64

In [5]:
for col in df.columns:
    if not col == 'user_id':
        print(df[col].unique())

<StringArray>
['-5', '30', 'unknown', nan, '45', '200', '18', '60', '25']
Length: 9, dtype: str
<StringArray>
['₹50000', '45000', '25000', nan, '120000.75', '78000']
Length: 6, dtype: str
<StringArray>
['HR', 'Finance', 'IT', nan, 'Sales', 'it ']
Length: 6, dtype: str
<StringArray>
['2020/12/01', '15/02/2021', nan, 'invalid', '2022-01-15']
Length: 5, dtype: str
<StringArray>
['DELHI', 'Delhi', 'Hyderabad', nan, 'mumbai', 'Bangalore', 'Mumbai']
Length: 7, dtype: str
<StringArray>
['3', 'excellent', nan, '5', 'poor', '4', '1', '2']
Length: 8, dtype: str
<StringArray>
['five', '1', '10', '5', '-1', '0', nan, '3']
Length: 8, dtype: str
<StringArray>
['True', 'yes', 'False', 'no', nan]
Length: 5, dtype: str

In [6]:
import numpy as np
df = df.replace(' ',np.nan)
df['user_id'] = df['user_id'].str.upper()
df['user_id'].head()

0    USER_0
1     U1001
2     U1002
3       NaN
4       NaN
Name: user_id, dtype: str

In [7]:
df.replace('unknown',np.nan,inplace=True)

,user_id,age,salary,department,join_date,city,performance_score,experience_years,is_active
0,USER_0,-5,₹50000,HR,2020/12/01,DELHI,3,five,True
1,U1001,30,45000,Finance,15/02/2021,Delhi,3,1,yes
2,U1002,30,25000,HR,NaN,Delhi,excellent,10,False
3,NaN,NaN,NaN,HR,invalid,Hyderabad,excellent,5,yes
4,NaN,NaN,120000.75,IT,NaN,DELHI,NaN,-1,False
...,...,...,...,...,...,...,...,...,...
995,NaN,60,₹50000,HR,15/02/2021,DELHI,2,five,NaN
996,U1996,NaN,NaN,IT,15/02/2021,Mumbai,NaN,5,no
997,USER_997,NaN,25000,HR,invalid,Mumbai,3,5,True
998,U1998,-5,25000,NaN,15/02/2021,Bangalore,1,0,True
999,NaN,30,45000,HR,2022-01-15,Hyderabad,excellent,five,no

In [8]:
df.replace('nan',np.nan,inplace=True)

,user_id,age,salary,department,join_date,city,performance_score,experience_years,is_active
0,USER_0,-5,₹50000,HR,2020/12/01,DELHI,3,five,True
1,U1001,30,45000,Finance,15/02/2021,Delhi,3,1,yes
2,U1002,30,25000,HR,NaN,Delhi,excellent,10,False
3,NaN,NaN,NaN,HR,invalid,Hyderabad,excellent,5,yes
4,NaN,NaN,120000.75,IT,NaN,DELHI,NaN,-1,False
...,...,...,...,...,...,...,...,...,...
995,NaN,60,₹50000,HR,15/02/2021,DELHI,2,five,NaN
996,U1996,NaN,NaN,IT,15/02/2021,Mumbai,NaN,5,no
997,USER_997,NaN,25000,HR,invalid,Mumbai,3,5,True
998,U1998,-5,25000,NaN,15/02/2021,Bangalore,1,0,True
999,NaN,30,45000,HR,2022-01-15,Hyderabad,excellent,five,no

In [9]:
df['age'].unique()

<StringArray>
['-5', '30', nan, '45', '200', '18', '60', '25']
Length: 8, dtype: str

In [10]:
df['age'] = df['age'].astype('float64')

In [11]:
df['age'].unique()

array([ -5.,  30.,  nan,  45., 200.,  18.,  60.,  25.])

In [12]:
df[(df['age']>100)|(df['age']<0)] = np.nan
df['age'].unique()

array([nan, 30., 45., 18., 60., 25.])

In [17]:
#6
#df['salary'].unique()
df['salary']=df['salary'].replace('₹50000',50000,inplace=True)

C:\Users\vinee\AppData\Local\Temp\ipykernel_13368\4240476010.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['salary']=df['salary'].replace('₹50000',50000,inplace=True)

In [18]:
df['salary'].unique()

array([nan, '45000', '25000', '120000.75', '78000', 50000], dtype=object)

In [19]:
df['salary'] = df['salary'].astype('float64')

In [ ]:
#7
df['join_date'] = df['join_date'].replace('invalid',np.nan,inplace=True)

C:\Users\vinee\AppData\Local\Temp\ipykernel_13368\562752343.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['join_date'] = df['join_date'].replace('invalid',np.nan,inplace=True)

In [30]:
df['join_date'].unique()

<StringArray>
[nan, '15/02/2021', '2022-01-15', '2020/12/01']
Length: 4, dtype: str

In [32]:
df['join_date'] = pd.to_datetime(df['join_date'],format="mixed")

In [33]:
#8
df['join_date'].unique()

<DatetimeArray>
['NaT', '2021-02-15 00:00:00', '2022-01-15 00:00:00', '2020-12-01 00:00:00']
Length: 4, dtype: datetime64[us]

In [41]:
df['joining_year'] = df['join_date'].dt.year
df.head()

,user_id,age,salary,department,join_date,city,performance_score,experience_years,is_active,joining_year
0,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
1,U1001,30.0,45000.00,Finance,2021-02-15,Delhi,3,1,yes,2021.0
2,U1002,30.0,25000.00,HR,NaT,Delhi,excellent,10,False,NaN
3,NaN,NaN,NaN,HR,NaT,Hyderabad,excellent,5,yes,NaN
4,NaN,NaN,120000.75,IT,NaT,DELHI,NaN,-1,False,NaN

In [42]:
df.columns

Index(['user_id', 'age', 'salary', 'department', 'join_date', 'city',
       'performance_score', 'experience_years', 'is_active', 'joining_year'],
      dtype='str')

In [45]:
#9
df['department'].unique()

<StringArray>
[nan, 'Finance', 'HR', 'IT', 'Sales', 'it ']
Length: 6, dtype: str

In [46]:
df['department'] = df['department'].str.strip().str.upper()

In [47]:
#10
df['city'].unique()

<StringArray>
[nan, 'Delhi', 'Hyderabad', 'DELHI', 'mumbai', 'Mumbai', 'Bangalore']
Length: 7, dtype: str

In [49]:
df['city'] = df['city'].str.title()

In [50]:
df['city'].unique()

<StringArray>
[nan, 'Delhi', 'Hyderabad', 'Mumbai', 'Bangalore']
Length: 5, dtype: str

In [51]:
#11
mapp = {
    "excellent" : 5,
    "4":4,
    "3":3,
    "2":2,
    "poor":1
    
}
df['performance_score']=df['performance_score'].map(mapp)

In [52]:
df['performance_score'].head()

0    NaN
1    3.0
2    5.0
3    5.0
4    NaN
Name: performance_score, dtype: float64

In [57]:
#12
df['experience_years'] = df['experience_years'].astype('float64')

In [58]:
df['experience_years'] = df['experience_years'].replace('five',5,inplace=True)

C:\Users\vinee\AppData\Local\Temp\ipykernel_13368\890157996.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['experience_years'] = df['experience_years'].replace('five',5,inplace=True)

In [59]:
df['experience_years'].unique()

array([nan,  1., 10.,  5., -1.,  0.,  3.])

In [61]:
df.loc[df['experience_years']<0,"experience_years"] = np.nan

In [62]:
#13
df['is_active'].unique()

<StringArray>
[nan, 'yes', 'False', 'no', 'True']
Length: 5, dtype: str

In [63]:
df['is_active'] = df['is_active'].replace({"yes":True,'no':False })

In [64]:
#14
df['user_id'].unique()

<StringArray>
[       nan,    'U1001',    'U1002',   'USER_5',   'USER_8',    'U1010',
  'USER_11',    'U1016',    'U1023',  'USER_28',
 ...
 'USER_964',    'U1967', 'USER_970',    'U1974', 'USER_976',    'U1988',
 'USER_989',    'U1991',    'U1996', 'USER_997']
Length: 368, dtype: str

In [67]:
df['user_id'] = df['user_id'].drop_duplicates()

In [68]:
#15
df.head()

,user_id,age,salary,department,join_date,city,performance_score,experience_years,is_active,joining_year
0,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
1,U1001,30.0,45000.00,FINANCE,2021-02-15,Delhi,3.0,1.0,True,2021.0
2,U1002,30.0,25000.00,HR,NaT,Delhi,5.0,10.0,False,NaN
3,NaN,NaN,NaN,HR,NaT,Hyderabad,5.0,5.0,True,NaN
4,NaN,NaN,120000.75,IT,NaT,Delhi,NaN,NaN,False,NaN

In [73]:
df = df.dropna(axis=0)

In [74]:
df.head()

,user_id,age,salary,department,join_date,city,performance_score,experience_years,is_active,joining_year
1,U1001,30.0,45000.0,FINANCE,2021-02-15,Delhi,3.0,1.0,True,2021.0
16,U1016,25.0,45000.0,FINANCE,2020-12-01,Delhi,4.0,1.0,True,2020.0
29,USER_29,25.0,25000.0,HR,2020-12-01,Delhi,1.0,3.0,True,2020.0
61,USER_61,25.0,50000.0,FINANCE,2020-12-01,Mumbai,3.0,10.0,True,2020.0
107,U1107,18.0,50000.0,IT,2021-02-15,Mumbai,1.0,5.0,False,2021.0